export const BookmarkTypes ={
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    EDIT_BOOKMARK: 'EDIT_BOOKMARK',
    DELETE_BOOKMARK: 'DELETE_BOOKMARK',
    GET_ALL_BOOKMARKS: 'GET_ALL_BOOKMARKS',
    PINNED_BOOKMARKS: 'PINNED_BOOKMARKS',
    CHANGE_THEME: 'CHANGE_THEME',
    LOGIN_USER: 'LOGIN_USER'
}